<?php
/**
 * Created by PhpStorm.
 * User: SEELE
 * Date: 2017/4/18
 * Time: 14:20
 */
namespace backend\controllers;
use yii\web\Controller;
class RedisController extends Controller{
    protected $redis = null;
    public function behaviors()
    {
        $this->redis = new \Redis();
        $this->redis->connect('127.0.0.1', 6379);
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionConnect(){
        $conn = $this->redis->connect('127.0.0.1', 6379);
        if($conn) {
            echo "Connection to server sucessfully<br>";
            echo "Server is running: " . $this->redis->ping();
            exit;
        }
    }

    public function actionInsertOne(){
        $this->redis->set("user_name", "jieguangyao2017" , 25);
    }

    public function actionGetOne(){
        $ret = $this->redis->get('user_name');
        var_dump($ret);
    }

    public function actionPush(){
        $this->redis->lpush("tutorial-list", "Redis22222");
        $this->redis->lpush("tutorial-list", "Mongodb22222");
        $this->redis->lpush("tutorial-list", "Mysql22222");
    }

    public function actionGetList(){
        $ret = $this->redis->lrange("tutorial-list");
        echo "Stored string in redis<br>";
        print_r($ret);
    }
}