<?php
/**
 * Created by PhpStorm.
 * User: kilo
 * Date: 2017/3/25
 * Time: 19:15
 */

namespace backend\models;

use yii\elasticsearch\ActiveRecord;

class ESearch extends ActiveRecord{
    public static function index()
    {
        return "catalog"; // TODO: Change the autogenerated stub
    }

    public static function type()
    {
        return "user"; // TODO: Change the autogenerated stub
    }

    public function attributes()
    {

//        $ret = ESearch::getScore();
//        var_dump($ret);die();
        return ['id', 'name', 'address', 'update_datetime'];

    }

    public static function updateRecord($book_id, $columns){
        try{
            $record = self::get($book_id);
            foreach($columns as $key => $value){
                $record->$key = $value;
            }

            return $record->update();
        }
        catch(\Exception $e){
            //handle error here
            return false;
        }
    }

    public static function createOne($book_id, $columns){
        try{
            $record = new ESearch();
            $record->primaryKey = $book_id;
            foreach($columns as $key => $value){
                $record->$key = $value;
            }

            return $record->save();
        }
        catch(\Exception $e){
            //handle error here
            return false;
        }
    }


}